version: "3"

services:
    nuxt:
        build: .
        container_name: nuxt
        working_dir: /usr/src/nuxt-app
        command: npm run dev
        volumes:
            - ./:/usr/src/nuxt-app
        ports:
            - ${NUXT_PORT}:3000
        environment:
            HOST: ${NUXT_HOST}

    yarn:
        build: .
        container_name: yarn
        working_dir: /usr/src/nuxt-app
        volumes:
            - ./:/usr/src/nuxt-app
        entrypoint: ["yarn"]
